### ISSUE TITLE
Audio classification sample fails with error: can't pickle local object 'main.<locals>.train_transforms'

### ISSUE THREAD

**Issue by ljaljushkin** [huggingface/optimum-intel#423]
Install optimum-intel from sources or via pip:
```
pip install --upgrade-strategy eager "optimum[openvino,nncf]"
```

Run cmd from the [README.md](https://github.com/huggingface/optimum-intel/blob/d78140794e0fb46ee2deccf8e48e733111b255f4/examples/openvino/audio-classification/README.md#fine-tuning-wav2vec2-on-keyword-spotting-with-qat)
```
python run_audio_classification.py     --model_name_or_path facebook/wav2vec2-base     --nncf_compression_config configs/wav2vec2-base-qat.json     --dataset_name superb     --dataset_config_name ks     --output_dir /tmp/qat-wav2vec2-base-ft-keyword-spotting     --overwrite_output_dir     --remove_unused_columns False     --do_train     --do_eval        --learning_rate 3e-5     --max_length_seconds 1     --attention_mask False     --warmup_ratio 0.1     --num_train_epochs 5     --per_device_train_batch_size 32     --gradient_accumulation_steps 4     --per_device_eval_batch_size 64     --dataloader_num_workers 4     --logging_strategy steps     --logging_steps 10     --evaluation_strategy epoch     --save_strategy epoch     --load_best_model_at_end True     --metric_for_best_model accuracy     --save_total_limit 3     --seed 42
```

It fails with the error:
```
can't pickle local object 'main.<locals>.train_transforms'
```
on iterating over train data:
```
model_inputs = next(iter(train_dataloader))
```

Full log:
```
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
/home/devuser/nlyalyus/env/optimum-intel/lib/python3.8/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
run_audio_classification.py:182: FutureWarning: The argument `--freeze_feature_extractor` is deprecated and will be removed in a future version. Use `--freeze_feature_encoder`instead. Setting `freeze_feature_encoder==True`.
  warnings.warn(
09/07/2023 13:52:56 - WARNING - __main__ - Process rank: 0, device: cpu, n_gpu: 0 distributed training: True, 16-bits training: False
/home/devuser/nlyalyus/env/optimum-intel/lib/python3.8/site-packages/datasets/load.py:2089: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=None' instead.
  warnings.warn(
/home/devuser/nlyalyus/env/optimum-intel/lib/python3.8/site-packages/transformers/configuration_utils.py:380: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
[WARNING|modeling_utils.py:3645] 2023-09-07 13:53:03,402 >> Some weights of Wav2Vec2ForSequenceClassification were not initialized from the model checkpoint at facebook/wav2vec2-base and are newly initialized: ['projector.bias', 'classifier.weight', 'projector.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "run_audio_classification.py", line 445, in <module>
    main()
  File "run_audio_classification.py", line 400, in main
    trainer = OVTrainer(
  File "/home/devuser/nlyalyus/env/optimum-intel/lib/python3.8/site-packages/optimum/intel/openvino/trainer.py", line 207, in __init__
    model_inputs = next(iter(train_dataloader))
  File "/home/devuser/nlyalyus/env/optimum-intel/lib/python3.8/site-packages/accelerate/data_loader.py", line 381, in __iter__
    dataloader_iter = super().__iter__()
  File "/home/devuser/nlyalyus/env/optimum-intel/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 441, in __iter__
    return self._get_iterator()
  File "/home/devuser/nlyalyus/env/optimum-intel/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/devuser/nlyalyus/env/optimum-intel/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1042, in __init__
    w.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.train_transforms'
```

@helena-intel @vuiseng9 @AlexKoff88 @echarlaix @yujiepan-work

**Comment by helena-intel** [comment]
The same issue was reported to optimum, and it was fixed in source there: https://github.com/huggingface/optimum/issues/1327
Installing optimum from source resolved this issue for me - but now I get the previously reported error "AttributeError: 'Wav2Vec2ForSequenceClassification' object has no attribute 'no_sync'" again  (https://github.com/huggingface/optimum-intel/issues/345).  @ljaljushkin could you try with optimum from source? Since you reported the no_sync issue fixed, perhaps that's something with my device/environment.

I will add tests for the examples so we can catch these issues earlier in the future. We can't test full training in Github Actions, but we can test that the basic functionality still works.
