### ISSUE TITLE
Quantization is failed on BF16 model

### ISSUE THREAD

**Issue by jiqing-feng** [huggingface/optimum-intel#51]
@echarlaix @PenghuiCheng @sywangyi 
Hi, I met an error while applying quantization on BF16 model. 

My running command: numactl --physcpubind=0-3 -m 0 python3 run_qa.py --model_name_or_path ./output_dir/bert-large-distill_MiniLM/squad_v1_output_test_bf16/ --dataset_name squad --apply_quantization --quantization_approach static --do_train --do_eval --verify_loading --num_train_epochs 1 --learning_rate 0 --overwrite_output_dir --output_dir ./output_dir/quantization/minilm-squad-static_bf16_int8_4_core --bf16 --no_cuda --use_ipex

Error info:
Traceback (most recent call last):
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.540", line 7, in forward
    quantize_per_tensor = torch.quantize_per_tensor(hidden_states, dense_input_scale_0, dense_input_zero_point_0, torch.quint8);  hidden_states = dense_input_scale_0 = dense_input_zero_point_0 = None
RuntimeError: Q
![error1](https://user-images.githubusercontent.com/107918818/192237466-05ac88e1-4de3-4c16-8f82-bc45d6130aca.png)
uantize only works on Float Tensor, got BFloat16

Call using an FX-traced Module, line 7 of the traced Module's generated forward function:
    dense_input_zero_point_0 = self.dense_input_zero_point_0
    quantize_per_tensor = torch.quantize_per_tensor(hidden_states, dense_input_scale_0, dense_input_zero_point_0, torch.quint8);  hidden_states = dense_input_scale_0 = dense_input_zero_point_0 = None

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    dense = self.dense(quantize_per_tensor);  quantize_per_tensor = None

    dequantize_1 = dense.dequantize();  dense = None

2022-09-26 02:52:52 [ERROR] Unexpected exception RuntimeError('Quantize only works on Float Tensor, got BFloat16') happened during tuning.

Traceback (most recent call last):
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/neural_compressor/experimental/quantization.py", line 148, in execute
    self.strategy.traverse()
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/neural_compressor/strategy/strategy.py", line 412, in traverse
    self.last_tune_result = self._evaluate(self.last_qmodel)
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/neural_compressor/strategy/strategy.py", line 520, in _evaluate
    val = self.objectives.evaluate(
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/neural_compressor/objective.py", line 266, in evaluate
    acc = eval_func(model)
  File "/global/panfs01/users/jiqingfe/examples/question-answering/run_qa.py", line 740, in eval_func
    return take_eval_steps(model, trainer, metric_name)
  File "/global/panfs01/users/jiqingfe/examples/question-answering/run_qa.py", line 733, in take_eval_steps
    metrics = trainer.evaluate()
  File "/global/panfs01/users/jiqingfe/examples/question-answering/trainer_qa.py", line 40, in evaluate
    output = eval_loop(
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/transformers/trainer.py", line 2965, in evaluation_loop
    loss, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/transformers/trainer.py", line 3216, in prediction_step
    outputs = model(**inputs)
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 1851, in forward
    outputs = self.bert(
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 1022, in forward
    encoder_outputs = self.encoder(
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 611, in forward
    layer_outputs = layer_module(
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 497, in forward
    self_attention_outputs = self.attention(
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 436, in forward
    attention_output = self.output(self_outputs[0], hidden_states)
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/torch/fx/graph_module.py", line 652, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/torch/fx/graph_module.py", line 275, in __call__
    raise e.with_traceback(None)
RuntimeError: Quantize only works on Float Tensor, got BFloat16
2022-09-26 02:52:52 [ERROR] Specified timeout or max trials is reached! Not found any quantized model which meet accuracy goal. Exit.
2022-09-26 02:52:52 [INFO] The following columns in the evaluation set don't have a corresponding argument in `NoneType.forward` and have been ignored: offset_mapping, example_id. If offset_mapping, example_id are
not expected by `NoneType.forward`,  you can safely ignore this message.
Traceback (most recent call last):
  File "/global/panfs01/users/jiqingfe/examples/question-answering/run_qa.py", line 922, in <module>
    main()
  File "/global/panfs01/users/jiqingfe/examples/question-answering/run_qa.py", line 891, in main
    result_optimized_model = take_eval_steps(optimized_model, trainer, metric_name, save_metrics=True)
  File "/global/panfs01/users/jiqingfe/examples/question-answering/run_qa.py", line 733, in take_eval_steps
    metrics = trainer.evaluate()
  File "/global/panfs01/users/jiqingfe/examples/question-answering/trainer_qa.py", line 40, in evaluate
    output = eval_loop(
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/transformers/trainer.py", line 2908, in evaluation_loop
    model = self._wrap_model(self.model, training=False, dataloader=dataloader)
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/transformers/trainer.py", line 1318, in _wrap_model
    model = self.ipex_optimize_model(model, training, dtype=dtype)
  File "/panfs/users/jiqingfe/miniconda3/envs/HuggingFace/lib/python3.9/site-packages/transformers/trainer.py", line 1304, in ipex_optimize_model
    model.eval()
AttributeError: 'NoneType' object has no attribute 'eval'

![error1](https://user-images.githubusercontent.com/107918818/192237565-24c87541-f6a0-4693-8bc2-a3728d240a96.png)

![error2](https://user-images.githubusercontent.com/107918818/192237607-442e8142-8752-4c77-94aa-531779590481.png)

**Comment by sywangyi** [comment]
@yao-matrix

**Comment by PenghuiCheng** [comment]
There is a feature gap from Huggingface and Optimum-intel, now optimum-intel didn't support IPEX model tuning with INC, we will consider adding this feature in the future.
