### ISSUE TITLE
OVStableDiffusionPipeline.from_pretrained() and LatentConsistencyModelPipeline.from_pretrained() cause an exception by running in Windows 

### ISSUE THREAD

**Issue by DimaPastushenkov** [huggingface/optimum-intel#555]
By calling OVStableDiffusionPipeline.from_pretrained() or LatentConsistencyModelPipeline.from_pretrained() in Windows an exception is produced:

Exception ignored in: <finalize object at 0x2525ced37a0; dead>
Traceback (most recent call last):
  File "C:\Users\dimap\AppData\Local\Programs\Python\Python311\Lib\weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimap\AppData\Local\Programs\Python\Python311\Lib\tempfile.py", line 894, in _cleanup
    cls._rmtree(name, ignore_errors=ignore_errors)
  File "C:\Users\dimap\AppData\Local\Programs\Python\Python311\Lib\tempfile.py", line 890, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Users\dimap\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimap\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 617, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\dimap\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\dimap\AppData\Local\Programs\Python\Python311\Lib\tempfile.py", line 881, in onerror
    cls._rmtree(path, ignore_errors=ignore_errors)
  File "C:\Users\dimap\AppData\Local\Programs\Python\Python311\Lib\tempfile.py", line 890, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Users\dimap\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimap\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 603, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Users\dimap\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 600, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
         ^^^^^^^^^^^^^^^^
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\dimap\\AppData\\Local\\Temp\\tmpm2wimoof\\text_encoder\\openvino_model.bin'

Optimum: 1.16.2
Optimum-Intel 1.15.0.dev0

It can be reproduced using https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/236-stable-diffusion-v2/236-stable-diffusion-v2-optimum-demo-comparison.ipynb

**Comment by helena-intel** [comment]
Thanks for reporting the issue! I could reproduce it with the notebook. I see a similar error, but after that, the model does work as expected and I see the generated image. But that error should not be there.

Smaller script to reproduce (saving the IR to verify that that does indeed work):

```
from optimum.intel.openvino import OVStableDiffusionPipeline

model_id = "hf-internal-testing/tiny-stable-diffusion-pipe-safetensors"
ov_pipe = OVStableDiffusionPipeline.from_pretrained(model_id, export=True, compile=False)
ov_pipe.reshape(batch_size=1, height=512, width=512, num_images_per_prompt=1)
ov_pipe.save_pretrained("./openvino_ir")
```
Tested with optimum 1.17.1, optimum-intel from source today (1.16.0.dev0) , diffusers 0.26.3, transformers 4.37.2 and torch 2.2.0. Python 3.10 on Windows 10. I didn't see it on Linux.
There was also no error on Windows when using ` optimum-cli export openvino -m hf-internal-testing/tiny-stable-diffusion-pipe-safetensors tiny-sd-ov` 

@echarlaix do you recognize this issue or could you have a look?
