### ISSUE TITLE
UnboundLocalError: local variable 'all_files' referenced before assignment

### ISSUE THREAD

**Issue by HenryZhuHR** [huggingface/optimum-intel#691]
I tried the [Quick tour](https://github.com/huggingface/optimum-intel#openvino) in `README.md`:
```
optimum-cli export openvino --model stabilityai/stable-diffusion-2-1 --dataset conceptual_captions --weight-format int8 ov_model
```
But an error is reported.
```shell
optimum-cli export openvino --model stabilityai/stable-diffusion-2-1 --dataset conceptual_captions --weight-format int8 ov_model
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
Traceback (most recent call last):
  File "/home/ubuntu/demo/.env//home/ubuntu/demobin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/demo/.env//home/ubuntu/demolib/python3.10/site-packages/optimum/commands/optimum_cli.py", line 163, in main
    service.run()
  File "/home/ubuntu/demo/.env//home/ubuntu/demolib/python3.10/site-packages/optimum/commands/export/openvino.py", line 221, in run
    library_name = TasksManager.infer_library_from_model(self.args.model, library_name=self.args.library)
  File "/home/ubuntu/demo/.env//home/ubuntu/demolib/python3.10/site-packages/optimum/exporters/tasks.py", line 1723, in infer_library_from_model
    all_files, _ = TasksManager.get_model_files(
  File "/home/ubuntu/demo/.env//home/ubuntu/demolib/python3.10/site-packages/optimum/exporters/tasks.py", line 1424, in get_model_files
    return all_files, request_exception
UnboundLocalError: local variable 'all_files' referenced before assignment
```

**Comment by echarlaix** [comment]
Hi @HenryZhuHR, I'm not able to reproduce your error with optimum v1.19.1, what optimum version do you use ?  Can you try :

```python
from optimum.exporters.tasks import TasksManager

all_files, _ = TasksManager.get_model_files("stabilityai/stable-diffusion-2-1")
```

**Comment by flyskywhy** [comment]
@henryzhuhr , I met the same error when using <https://github.com/rupeshs/fastsdcpu> even I put e.g. `sdxs-512-0.9-openvino/` into `fastsdcpu/configs/rupeshs/` as described in `fastsdcpu/configs/openvino-lcm-models.txt`.

I solved the error: just replace `rupeshs/sdxs-512-0.9-openvino` into `/home/foo/bar/fastsdcpu/configs/rupeshs/sdxs-512-0.9-openvino` in `fastsdcpu/configs/openvino-lcm-models.txt`.

So maybe you can try replace your `--model stabilityai/stable-diffusion-2-1` into `--model /home/foo/bar/stabilityai/stable-diffusion-2-1`?
