### ISSUE TITLE
OVModelForCausalLM: "index out of range in self" at torch.embedding

### ISSUE THREAD

**Issue by dkurt** [huggingface/optimum-intel#90]
[Model](https://huggingface.co/sberbank-ai/rugpt3medium_based_on_gpt2) is converted fine by `torch.onnx`:
```python
model = GPT2LMHeadModel.from_pretrained(f"sberbank-ai/rugpt3medium_based_on_gpt2")

dummy_input_ids = torch.randint(0, 255, (1, 11))
dummy_mask = torch.randint(0, 2, (1, 11))

torch.onnx.export(
    model,
    (dummy_input_ids, None, dummy_mask),
    "rugpt3medium_based_on_gpt2.onnx",
    input_names=["input_ids", "attention_mask"],
    output_names=["output"],
    opset_version=13
)
```
but not through Optimum API:
```python
model = OVModelForCausalLM.from_pretrained(f"sberbank-ai/rugpt3medium_based_on_gpt2", from_transformers=True)
```
Error:
```
./venv3/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py:796: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if batch_size <= 0:
Traceback (most recent call last):
  File "run.py", line 165, in <module>
    ov_model = ov_constructor.from_pretrained(f"sberbank-ai/{name}", from_transformers=True)
  File "./venv3/lib/python3.8/site-packages/optimum/modeling_base.py", line 232, in from_pretrained
    return cls._from_transformers(
  File "./venv3/lib/python3.8/site-packages/optimum/intel/openvino/modeling_base.py", line 234, in _from_transformers
    export(
  File "./venv3/lib/python3.8/site-packages/transformers/onnx/convert.py", line 339, in export
    return export_pytorch(preprocessor, model, config, opset, output, tokenizer=tokenizer, device=device)
  File "./venv3/lib/python3.8/site-packages/transformers/onnx/convert.py", line 192, in export_pytorch
    onnx_export(
  File "./venv3/lib/python3.8/site-packages/torch/onnx/__init__.py", line 350, in export
    return utils.export(
  File "./venv3/lib/python3.8/site-packages/torch/onnx/utils.py", line 163, in export
    _export(
  File "./venv3/lib/python3.8/site-packages/torch/onnx/utils.py", line 1074, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "./venv3/lib/python3.8/site-packages/torch/onnx/utils.py", line 727, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "./venv3/lib/python3.8/site-packages/torch/onnx/utils.py", line 602, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "./venv3/lib/python3.8/site-packages/torch/onnx/utils.py", line 517, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "./venv3/lib/python3.8/site-packages/torch/jit/_trace.py", line 1175, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "./venv3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "./venv3/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "./venv3/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "./venv3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "./venv3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "./venv3/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1046, in forward
    transformer_outputs = self.transformer(
  File "./venv3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "./venv3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "./venv3/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 832, in forward
    inputs_embeds = self.wte(input_ids)
  File "./venv3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "./venv3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "./venv3/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "./venv3/lib/python3.8/site-packages/torch/nn/functional.py", line 2199, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```

**Comment by echarlaix** [comment]
Hi @dkurt, 

I was not able to reproduce this error, can you confirm that you still observe it with the following dependencies:
```
openvino==2022.3.0
optimum==1.6.3
optimum-intel==1.6.1
```

**Comment by dkurt** [comment]
Thanks, @echarlaix! Can confirm that problem is solved with latest version of package.
